# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorTable',
            fields=[
                ('actorid', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=140)),
                ('gravatar_id', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=140)),
                ('avatar_url', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='CommitTable',
            fields=[
                ('actorid', models.CharField(max_length=140)),
                ('sha', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=140)),
                ('message', models.CharField(max_length=140)),
                ('distinct', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=140)),
                ('actorid', models.CharField(max_length=140)),
                ('repoid', models.CharField(max_length=140)),
                ('payloadid', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadTable',
            fields=[
                ('pushid', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=140)),
                ('distinct_size', models.CharField(max_length=140)),
                ('ref', models.CharField(max_length=140)),
                ('head', models.CharField(max_length=140)),
                ('before', models.CharField(max_length=140)),
                ('commitid', models.CharField(max_length=140)),
                ('public', models.CharField(max_length=140)),
                ('created_at', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='RepoTable',
            fields=[
                ('repoid', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('url', models.TextField(max_length=1000)),
            ],
        ),
    ]
