# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='ActorTable',
        ),
        migrations.DeleteModel(
            name='CommitTable',
        ),
        migrations.DeleteModel(
            name='EventTable',
        ),
        migrations.DeleteModel(
            name='PayloadTable',
        ),
        migrations.DeleteModel(
            name='RepoTable',
        ),
    ]
